# Generated by Django 3.0.2 on 2022-12-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tetrisresult',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
