# Generated by Django 3.0.2 on 2022-12-29 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tetris', '0002_auto_20221213_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSeasonRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockcount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tetris.User')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockcount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tetris.User')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockcount', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tetris.User')),
            ],
        ),
        migrations.DeleteModel(
            name='TetrisResult',
        ),
    ]
